MvcWeb/MvcWeb/Controllers/CouresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWeb.Controllers
{
    public class CouresController : Controller
    {
        Business.coures coures = new Business.coures();

        //显示所有数据
        public ActionResult CouresList()
        {
            return View(coures.Get(""));
        }

        //根据ID删除该列数据
        public ActionResult CouresDelete(string id)
        {
            coures.Delete(id);
            Response.Write("<script>alert('删除成功!');location.href='/Coures/CouresList'</script>");
            return null;
        }

        //根据ID导出该列数据
        public ActionResult CouresEdit(string id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                MvcModel.couresData couresdata = coures.SelectData(string.Format(" and id = {0}", id));
                return View(couresdata);
            }
        }

        //添加或者修改该列数据
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult CouresEdit(MvcModel.couresData couresdata)
        {
            if (ModelState.IsValid)
            {
                if (couresdata.Id == 0)
                {
                    coures.Insert(couresdata);
                    Response.Write("<script>alert('添加成功!');location.href='/coures/couresList'</script>");
                }
                else
                {
                    coures.Modify(couresdata);
                    Response.Write("<script>alert('修改成功!');location.href='/coures/couresList'</script>");
                }

                return null;
            }
            return View(couresdata);
        }

        //显示所有数据-前台
        public ActionResult HomeCouresList()
        {
            return View(coures.Get(""));
        }

        //根据ID删除该列数据
        public ActionResult HomeCouresDelete(string id)
        {
            coures.Delete(id);
            Response.Write("<script>alert('删除成功!');location.href='/Coures/HomeCouresList'</script>");
            return null;
        }

        //根据ID导出该列数据
        public ActionResult HomeCouresEdit(string id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                MvcModel.couresData couresdata = coures.SelectData(string.Format(" and id = {0}", id));
                return View(couresdata);
            }
        }

        //添加或者修改该列数据
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult HomeCouresEdit(MvcModel.couresData couresdata)
        {
            if (ModelState.IsValid)
            {
                if (couresdata.Id == null)
                {
                    coures.Insert(couresdata);
                    Response.Write("<script>alert('添加成功!');location.href='/Coures/HomeCouresList'</script>");
                }
                else
                {
                    coures.Modify(couresdata);
                    Response.Write("<script>alert('修改成功!');location.href='/Coures/HomeCouresList'</script>");
                }

                return null;
            }
            return View(couresdata);
        }

    }
}

MvcWeb/MvcWeb/Views/Coures/CouresEdit.cshtml
@{
    ViewBag.Title = "CouresEdit";
    Layout = "~/Views/Shared/_Home.cshtml";
}

@model MvcModel.couresData

<div class="right" id="mainFrame">
    <div class="right_cont">
        <ul class="breadcrumb">
            当前位置：
            <a href="#">首页</a>
            <span class="divider">/</span>课程编辑
        </ul>
        <div class="title_right"><strong>课程编辑</strong></div>
        <div style="width:900px; margin:auto">
            @using (Html.BeginForm("CouresEdit", "Coures", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                <table class="table table-bordered">
                  <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">课程名称：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.coursename, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.coursename)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">任课老师：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.theter, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.theter)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">上课地点：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.theaddress, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.theaddress)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">上课时间：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.thetime, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.thetime)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">学时：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.thexs, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.thexs)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">学分：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.thexf, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.thexf)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">说明：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.memos, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.memos)</span>
                    </tr>
                     
                </table>
                <table class="margin-bottom-20 table  no-border">
                    <tr>
                        <td class="text-center">
                            <input type="submit" value="确定" class="btn btn-info " style="width:80px;" />
                        </td>
                    </tr>
                </table>
            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Coures/CouresList.cshtml
@{
    ViewBag.Title = "CouresList";
    Layout = "~/Views/Shared/_Home.cshtml";
}

@model System.Data.DataTable

<div class="right" id="mainFrame">

    <div class="right_cont">
        <ul class="breadcrumb">
            当前位置：
            <a href="#">首页</a>
            <span class="divider">/</span>
            课程列表
        </ul>

        <table class="table table-bordered table-striped table-hover">
            <tbody>
                <tr align="center">
                 <td nowrap="nowrap"><strong>课程名称</strong></td><td nowrap="nowrap"><strong>任课老师</strong></td><td nowrap="nowrap"><strong>上课地点</strong></td><td nowrap="nowrap"><strong>上课时间</strong></td><td nowrap="nowrap"><strong>学时</strong></td><td nowrap="nowrap"><strong>学分</strong></td><td nowrap="nowrap"><strong>说明</strong></td>
                    <td width="80" nowrap="nowrap"><strong> 操作 </strong></td>
                </tr>
                @foreach (System.Data.DataRow dr in Model.Rows)
                {
                    <tr align="center">
                        <td nowrap="nowrap">@dr["coursename"] </td><td nowrap="nowrap">@dr["theter"] </td><td nowrap="nowrap">@dr["theaddress"] </td><td nowrap="nowrap">@dr["thetime"] </td><td nowrap="nowrap">@dr["thexs"] </td><td nowrap="nowrap">@dr["thexf"] </td><td nowrap="nowrap">@dr["memos"] </td>
                        <td nowrap="nowrap">
                            @Html.ActionLink("编辑", "CouresEdit", new { id = @dr["id"] })
                            @Html.ActionLink("删除", "CouresDelete", new { id = @dr["id"] })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>