MvcWeb/MvcWeb/Controllers/ForleaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWeb.Controllers
{
    public class ForleaveController : Controller
    {
        Business.forleave forleave = new Business.forleave();

        //显示所有数据
        public ActionResult ForleaveList()
        {
            return View(forleave.Get(""));
        }

        //根据ID删除该列数据
        public ActionResult ForleaveDelete(string id)
        {
            forleave.Delete(id);
            Response.Write("<script>alert('删除成功!');location.href='/Forleave/ForleaveList'</script>");
            return null;
        }

        //根据ID导出该列数据
        public ActionResult ForleaveEdit(string id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                MvcModel.forleaveData forleavedata = forleave.SelectData(string.Format(" and id = {0}", id));
                return View(forleavedata);
            }
        }

        //添加或者修改该列数据
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ForleaveEdit(MvcModel.forleaveData forleavedata)
        {
            if (ModelState.IsValid)
            {
                if (forleavedata.Id == 0)
                {
                    forleave.Insert(forleavedata);
                    Response.Write("<script>alert('添加成功!');location.href='/forleave/forleaveList'</script>");
                }
                else
                {
                    forleave.Modify(forleavedata);
                    Response.Write("<script>alert('修改成功!');location.href='/forleave/forleaveList'</script>");
                }

                return null;
            }
            return View(forleavedata);
        }

        //显示所有数据-前台
        public ActionResult HomeForleaveList()
        {
            return View(forleave.Get(""));
        }

        //根据ID删除该列数据
        public ActionResult HomeForleaveDelete(string id)
        {
            forleave.Delete(id);
            Response.Write("<script>alert('删除成功!');location.href='/Forleave/HomeForleaveList'</script>");
            return null;
        }

        //根据ID导出该列数据
        public ActionResult HomeForleaveEdit(string id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                MvcModel.forleaveData forleavedata = forleave.SelectData(string.Format(" and id = {0}", id));
                return View(forleavedata);
            }
        }

        //添加或者修改该列数据
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult HomeForleaveEdit(MvcModel.forleaveData forleavedata)
        {
            if (ModelState.IsValid)
            {
                if (forleavedata.Id == null)
                {
                    forleave.Insert(forleavedata);
                    Response.Write("<script>alert('添加成功!');location.href='/Forleave/HomeForleaveList'</script>");
                }
                else
                {
                    forleave.Modify(forleavedata);
                    Response.Write("<script>alert('修改成功!');location.href='/Forleave/HomeForleaveList'</script>");
                }

                return null;
            }
            return View(forleavedata);
        }

    }
}

MvcWeb/MvcWeb/Views/Forleave/ForleaveEdit.cshtml
@{
    ViewBag.Title = "ForleaveEdit";
    Layout = "~/Views/Shared/_Home.cshtml";
}

@model MvcModel.forleaveData

<div class="right" id="mainFrame">
    <div class="right_cont">
        <ul class="breadcrumb">
            当前位置：
            <a href="#">首页</a>
            <span class="divider">/</span>请假编辑
        </ul>
        <div class="title_right"><strong>请假编辑</strong></div>
        <div style="width:900px; margin:auto">
            @using (Html.BeginForm("ForleaveEdit", "Forleave", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                <table class="table table-bordered">
                  <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">用户账号：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.userid, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.userid)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">申请时间：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.thetime, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.thetime)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">起始时间：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.starttime, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.starttime)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">结束时间：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.endtime, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.endtime)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">请假种类：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.thetype, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.thetype)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">请假说明：</td>
                        <td width="38%">
                            @Html.TextBoxFor(model => model.memos, new { @class = "span1-1" })
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.memos)</span>
                    </tr>
                     <tr>
                        <td width="12%" align="right" nowrap="nowrap" bgcolor="#f1f1f1">状态：</td>
                        <td width="38%">
                            <select name="status">
                                <option value="同意">同意</option>
                                <option value="驳回">驳回</option>
                            </select>
                            <span style="color:red;">@Html.ValidationMessageFor(model => model.status)</span>
                    </tr>
                     
                </table>
                <table class="margin-bottom-20 table  no-border">
                    <tr>
                        <td class="text-center">
                            <input type="submit" value="确定" class="btn btn-info " style="width:80px;" />
                        </td>
                    </tr>
                </table>
            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Forleave/ForleaveList.cshtml
@{
    ViewBag.Title = "ForleaveList";
    Layout = "~/Views/Shared/_Home.cshtml";
}

@model System.Data.DataTable

<div class="right" id="mainFrame">

    <div class="right_cont">
        <ul class="breadcrumb">
            当前位置：
            <a href="#">首页</a>
            <span class="divider">/</span>
            请假列表
        </ul>

        <table class="table table-bordered table-striped table-hover">
            <tbody>
                <tr align="center">
                 <td nowrap="nowrap"><strong>用户账号</strong></td><td nowrap="nowrap"><strong>申请时间</strong></td><td nowrap="nowrap"><strong>起始时间</strong></td><td nowrap="nowrap"><strong>结束时间</strong></td><td nowrap="nowrap"><strong>请假种类</strong></td><td nowrap="nowrap"><strong>请假说明</strong></td><td nowrap="nowrap"><strong>状态</strong></td>
                    <td width="80" nowrap="nowrap"><strong> 操作 </strong></td>
                </tr>
                @foreach (System.Data.DataRow dr in Model.Rows)
                {
                    <tr align="center">
                        <td nowrap="nowrap">@dr["userid"] </td><td nowrap="nowrap">@dr["thetime"] </td><td nowrap="nowrap">@dr["starttime"] </td><td nowrap="nowrap">@dr["endtime"] </td><td nowrap="nowrap">@dr["thetype"] </td><td nowrap="nowrap">@dr["memos"] </td><td nowrap="nowrap">@dr["status"] </td>
                        <td nowrap="nowrap">
                            @Html.ActionLink("编辑", "ForleaveEdit", new { id = @dr["id"] })
                            @Html.ActionLink("删除", "ForleaveDelete", new { id = @dr["id"] })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>